### ISSUE TITLE
oraclejdk13@13.0.1-9: download via aria2 failed

### ISSUE THREAD

**Issue by gitHubForLz** [ScoopInstaller/Java#110]
Download: If there are any errors, then see the log file. See '-l' option in help/man page for details.
ERROR Download failed! (Error 1) An unknown error occurred
ERROR https://download.oracle.com/otn-pub/java/jdk/13.0.1+9/cec27d702aa74d5a8630c65ae61e4305/jdk-13.0.1_windows-x64_bin.zip
    referer=https://download.oracle.com/otn-pub/java/jdk/13.0.1+9/cec27d702aa74d5a8630c65ae61e4305/
    dir=C:\Users\li\scoop\cache
    out=oraclejdk13#13.0.1-9#https_download.oracle.com_otn-pub_java_jdk_13.0.1_9_cec27d702aa74d5a8630c65ae61e4305_jdk-13.0.1_windows-x64_bin.zip

ERROR & 'D:\GlobalScoopApps\apps\aria2\current\aria2c.exe' --input-file='C:\Users\li\scoop\cache\oraclejdk13.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=16 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=30252 --continue --header='Cookie: oraclelicense=accept-securebackup-cookie'

**Comment by se35710** [comment]
Unable to reproduce.
