### ISSUE TITLE
How to use oraclejdk@1.8.0_45

### ISSUE THREAD

**Issue by willyyang** [ScoopInstaller/Java#113]
Hi, after running `scoop install oraclejdk@1.8.0_45` I see the following after running `scoop list`.. Where are the binaries associated? There's only a json file. 

Thanks.
```
  openjdk7-unofficial 7u80-b32 [java]
  oraclejdk 1.8.0_45 [C:\Users\xx\scoop\workspace\oraclejdk.json]
  oraclejdk13 13.0.1-9 [java]
```

**Comment by se35710** [comment]
Uninstall oraclejdk and install again.

```
PS C:> scoop uninstall oraclejdk
PS C:> scoop install oraclejdk
```

Please note that Java 8 JDK:s are behind a login page, and therefor are not available through this Scoop repository.
