### ISSUE TITLE
ojdkbuild11-full@11.0.5.10-2: decompress error

### ISSUE THREAD

**Issue by dengsx** [ScoopInstaller/Java#118]
Failed to extract files from C:\Users\002908\scoop\apps\ojdkbuild11-full\11.0.5.10-2\java-11-openjdk-11.0.5.10-2.windows.ojdkbuild.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild11-full\11.0.5.10-2\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Java/issues/new?title=ojdkbuild11-full%4011.0.5.10-2%3a+decompress+error

**Comment by bernstein82** [comment]
see solution in #82
> Run `scoop config MSIEXTRACT_USE_LESSMSI $true` and then uninstall, install.
