### ISSUE TITLE
Liberica JDK upgrades

### ISSUE THREAD

**Issue by hrstoyanov** [ScoopInstaller/Java#123]
Please upgrade the following in ```bucket```: 
- liberica13.json -> 13.0.2
- liberica11.json - > 11.0.6
- liberica8.json, liberica8-jre.json ->  8u242

**Comment by se35710** [comment]
Use https://api.bell-sw.com/api.html for autoupdate

**Comment by se35710** [comment]
For PR #127, #128, #129 and #130, could you please add autoupdate functionality via the API mentioned above.

**Comment by hrstoyanov** [comment]
I will take a look at the API, but maybe @voitylov , @bell-sw, from [bell-soft](https://bell-sw.com) will want to take charge of  #127, #128, #129 and #130?

**Comment by voitylov** [comment]
on behalf of @bell-sw : we'll be happy to help switch this over to the API version ourselves. Maybe a little later, closer to the next release in April. Meanwhile, is there a reason not to commit the changes as is?

**Comment by se35710** [comment]
@voitylov @bell-sw: I took some time to update current and add missing Liberica manifests using the BellSoft API. Please feel free to change them and add new releases when they arrive in April.

**Comment by hrstoyanov** [comment]
@se35710 @voitylov  - thank you!
