### ISSUE TITLE
Any possible that add openjfx into the bucket 

### ISSUE THREAD

**Issue by amaothree** [ScoopInstaller/Java#131]
website👇
https://openjfx.io/

**Comment by se35710** [comment]
Yes, OpenJFX from Gluon could be added. Please feel free to submit a PR.

Documentation on how to write a manifest: https://github.com/lukesampson/scoop/wiki/App-Manifests
...and how to make sure it autoupdates: https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate
