### ISSUE TITLE
oraclejdk@14-36: hash check failed

### ISSUE THREAD

**Issue by yao00jun** [ScoopInstaller/Java#152]
Checking hash of jdk-14_windows-x64_bin.zip ... ERROR Hash check failed!
App:         java/oraclejdk
URL:         https://download.oracle.com/otn-pub/java/jdk/14+36/076bab302c7b4508975440c56f6cc26a/jdk-14_windows-x64_bin.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    80212f7748c2671b89b6085000717c747851db004409dce3bb97f3a2aeb91cdd
Actual:      86e1783de07ff523cb245de5ecd6677a78132412eccc02d90ac0d6307b222395

**Comment by se35710** [comment]
Fixed in #151 , but your "Actual" hash is not correct, it should be `062284b1e79d2444c5da0c77e0820ee5177e503f9943d59c86c17c73c8ae7cd0`, see https://www.oracle.com/webfolder/s/digest/14checksum.html
