### ISSUE TITLE
ojdkbuild-full@14.0.1.7-1: Extracting error

### ISSUE THREAD

**Issue by digitalentiert** [ScoopInstaller/Java#167]
Line |
510 | throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
| ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Could not find 'java-14-openjdk-14.0.1-0'! (error 16)

**Comment by se35710** [comment]
It's not clear how to parse for the the correct extraction path. The download URL is [..]java-14-openjdk-14.0.1.7-**0**/java-14-openjdk-14.0.1.7-**1**.windows.ojdkbuild.x86_64.msi, and historically we have used the folder path, not the filename path.

I'll submit a PR manually changing `extract_dir` to `ojdkbuild\\java-14-openjdk-14.0.1-1`.
