### ISSUE TITLE
Update zulu JDK to actual versions

### ISSUE THREAD

**Issue by altro3** [ScoopInstaller/Java#169]
Need to update zulu JDK versions:

```
zulu13 ---> 13.31.11 (JDK 13.0.3+3)
zulu11 ---> 11.39.15 (JDK 11.0.7+10)
zulu8  ---> 8.46.0.19 (JDK 1.8u252b14)
```

**Comment by se35710** [comment]
There is an issue with Azul Systems API. Once they have fixed that, the Zulu manifest will update themselves.

If you don't want to wait, please submit a PR with updated manifests.

**Comment by guerra08** [comment]
Has Azul fixed the API on their end? Noticed that the current version is sill behind the latest release.

**Comment by se35710** [comment]
Zulu API is working now, closing this.

**Comment by se35710** [comment]
Latest versions update did work with the exception of Java 8, where the normal jdk api request still returns the FX version:

https://api.azul.com/zulu/download/community/v1.0/bundles/latest/?jdk_version=8&bundle_type=jre&features=headfull&ext=zip&os=windows&arch=x86&hw_bitness=64

```JSON
{
    "id": 27253,
    "url": "https://cdn.azul.com/zulu/bin/zulu8.50.0.53-ca-fx-jre8.0.275-win_x64.zip",
    "arch": "x86",
    "abi": "any",
    "hw_bitness": "64",
    "os": "windows",
    "ext": "zip",
    "bundle_type": "jre",
    "release_status": "ga",
    "support_term": "lts",
    "last_modified": "2020-11-16T14:53:38Z",
    "name": "zulu8.50.0.53-ca-fx-jre8.0.275-win_x64.zip",
    "zulu_version": [
        8,
        50,
        0,
        53
    ],
    "jdk_version": [
        8,
        0,
        275,
        1
    ],
    "size": 74852400,
    "md5_hash": "655c5fa5394c42895feabd612ab609fe",
    "sha256_hash": "1e5c6a830d75799d9bc36dce2fcac42a1db0fde54d7ae0f5c8cdd91275113724",
    "javafx": true,
    "features": [
        "fx",
        "headfull"
    ]
}
```
