### ISSUE TITLE
ojdkbuild11-full@11.0.7.10-1: decompress error

### ISSUE THREAD

**Issue by alexiskapit** [ScoopInstaller/Java#179]
Failed to extract files from C:\Users\jenkins\scoop\apps\ojdkbuild11-full\11.0.7.10-1\java-11-openjdk-11.0.7.10-1.windows.ojdkbuild.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild11-full\11.0.7.10-1\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Java/issues/new?title=ojdkbuild11-full%4011.0.7.10-1%3a+decompress+error

~\scoop\apps\ojdkbuild11-full\11.0.7.10-1\msi.log
=== Logging started: 5/22/2020  7:53:51 ===
Error 1304. Error writing to file: C:\Users\jenkins\scoop\apps\ojdkbuild11-full\11.0.7.10-1\_tmp\SourceDir\ojdkbuild\java-11-openjdk-11.0.7-1\missioncontrol\features\org.openjdk.jmc.feature.rcp.zh_CN_7.0.0.v20200417-1717\META-INF\maven\org.open
jdk.jmc\org.openjdk.jmc.feature.rcp.zh_CN\pom.properties. Verify that you have access to that directory.
=== Logging stopped: 5/22/2020  7:53:53 ===

**Comment by se35710** [comment]
Please run `scoop checkup` and paste the output here,

**Comment by alexiskapit** [comment]
"No problems identified!"

It seems to be related to file name limitation on Windows Server 2016. I've tried to enable long filename support but without any success.

**Comment by se35710** [comment]
Can you try again using lessmsi?
```
scoop install lessmsi
scoop config MSIEXTRACT_USE_LESSMSI $true
```

**Comment by alexiskapit** [comment]
Thanks, it worked !
