### ISSUE TITLE
ojdkbuild11-full@11.0.7.10-1: decompress error

### ISSUE THREAD

**Issue by cccxu** [ScoopInstaller/Java#180]
# error code : 1603
# error log
Error 1320. The specified path is too long: C:\Users\xuhao\scoop\apps\ojdkbuild11-full\11.0.7.10-1\_tmp\SourceDir\ojdkbuild\java-11-openjdk-11.0.7-1\missioncontrol\features\org.openjdk.jmc.feature.rcp.zh_CN_7.0.0.v20200417-1717\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.rcp.zh_CN

**Comment by se35710** [comment]
See issue #179. If non of the solutions works there, please open this issue again.
