### ISSUE TITLE
can not install oraclejdk

### ISSUE THREAD

**Issue by Jacky486** [ScoopInstaller/Java#182]
The remote server returned an error: (302) Moved Temporarily.
URL https://download.oracle.com/otn-pub/java/jdk/14.0.1+7/664493ef4a6946b186ff29eb326336a2/jdk-14.0.1_windows-x64_bin.zip is not valid

**Comment by brunovieira97** [comment]
This happens to me too, but only when calling Scoop from PowerShell 7. When using PowerShell 5.1 (the one that comes preinstalled on Windows 10), OracleJDK is installed without any errors.

**Comment by themrhead** [comment]
It also works invoking scoop install oraclejdk from Command Prompt (cmd), regardless inside Windows Terminal or directly from Comand Prompt session.

**Comment by se35710** [comment]
The fix for this problem is in https://github.com/lukesampson/scoop/pull/3902, and is available in the [develop](https://github.com/lukesampson/scoop/tree/develop) branch.

**Comment by se35710** [comment]
Fix is now in the master branch through commit https://github.com/lukesampson/scoop/commit/643cfb0da8369dbbe2964511698763c5ff179492
