### ISSUE TITLE
oraclejre8@8u261: download via aria2 failed

### ISSUE THREAD

**Issue by mikepruett3** [ScoopInstaller/Java#184]
ERROR Download failed! (Error 3) Resource was not found
ERROR https://javadl.oracle.com/webapps/download/AutoDL?BundleId=242061_a4634525489241b9a9e1aa73d9e118e6#/dl.tar.gz
    referer=https://javadl.oracle.com/webapps/download/AutoDL?BundleId=242061_a4634525489241b9a9e1aa73d9e118e6#/
    dir=C:\Users\<username>\scoop\cache
    out=oraclejre8#8u261#https_javadl.oracle.com_webapps_download_AutoDL_BundleId_242061_a4634525489241b9a9e1aa73d9e118e6_dl.tar.gz

**Comment by se35710** [comment]
Fixed in https://github.com/ScoopInstaller/Java/commit/47a13e555565377804c4901c8dc140831a9ccb2d
