### ISSUE TITLE
GraalVM was downgraded to 19.3

### ISSUE THREAD

**Issue by gdoenlen** [ScoopInstaller/Java#188]
It looks like a few weeks ago GraalVM was downgraded to 19.3 from the 20.x.x version. This seems to be incorrect as the 20.1.0 version was released in May and tomorrow 20.2.0 will be released. It looks like it was downgraded when the 19.3 Critical Patch Update came out. 

See the version roadmap here: https://www.graalvm.org/docs/release-notes/version-roadmap/

**Comment by se35710** [comment]
We get the current version from their Github latest release https://github.com/graalvm/graalvm-ce-builds/releases/latest, which currently points to 19.3. I think this is an issue with their Github release tagging, and not with the manifest.

**Comment by gdoenlen** [comment]
Yes it looks like 19.3 was marked as the latest release when they released the critical patch update. It seems like you're going to forever go in this cycle of 19.x -> 20.x -> 19.x whenever they release a patch release for the older version.

**Comment by gdoenlen** [comment]
Looks like you updated to 20.2 since thats the *latest release* on their github now, but we should avoid the upgrade/downgrade cycle when 19.3.4 comes out on [November 3rd](https://www.graalvm.org/release-notes/version-roadmap/).

**Comment by se35710** [comment]
@gdoenlen Is there any value adding both versions as separate manifests? Right now, the version check is just Github releases, so the checkver has to be updated to specify the correct major version.

**Comment by gdoenlen** [comment]
If they're supported I don't see why there wouldn't be value in having both versions available. The bucket has just about every version for everything doesn't it? 

Not sure what you would call them though. Current and ...?
