### ISSUE TITLE
ojdkbuild8-full@1.8.0.265-1.b01: decompress error

### ISSUE THREAD

**Issue by ChanthMiao** [ScoopInstaller/Java#191]
- error msg
![image](https://user-images.githubusercontent.com/39488343/91787057-95e10880-ec3b-11ea-90b4-2e45598c17f3.png)

- log content
![image](https://user-images.githubusercontent.com/39488343/91787092-a6917e80-ec3b-11ea-8c86-9e343597c787.png)

**Comment by se35710** [comment]
Please run `scoop checkup` before submitting issues.

**Comment by ChanthMiao** [comment]
> Please run `scoop checkup` before submitting issues.

1. Already checked, no problems reported.
2. Sorry for duplicate isuesses, which I did not notice.
3. decompresss error still exists in my computer environment.

**Comment by ChanthMiao** [comment]
> Please run `scoop checkup` before submitting issues.

It makes no sense. It just not work.

![image](https://user-images.githubusercontent.com/39488343/92312814-18c8e100-eff7-11ea-8cce-5cfc0e10fda9.png)

**Comment by ChanthMiao** [comment]
> Please run `scoop checkup` before submitting issues.

Please reopen this isuss, it really  matters.

P.S. My OS version:  WIndows 10 Pro v1909(18363.1049)

**Comment by ChanthMiao** [comment]
Fine, enable lessmsi, it works now.

**Comment by se35710** [comment]
My mistake, I thought it was long paths issues, but it was lessmsi. Happy you got it working!

**Comment by se35710** [comment]
I have updated the Wiki to clarify the lessmsi requirement: https://github.com/lukesampson/scoop/wiki/Java#ojdkbuild
