### ISSUE TITLE
ojdkbuild8-full@1.8.0.265-1.b01: decompress error

### ISSUE THREAD

**Issue by peng-an** [ScoopInstaller/Java#192]
λ scoop install ojdkbuild8-full
Installing 'ojdkbuild8-full' (1.8.0.265-1.b01) [64bit]
Loading java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi from cache
Checking hash of java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi ... ok.
Extracting java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\******\scoop\apps\ojdkbuild8-full\1.8.0.265-1.b01\java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild8-full\1.8.0.265-1.b01\msi.log

**msi.log**
=== Logging started: 9/2/2020  11:00:22 ===
Error 1320. The specified path is too long: C:\Users\******\scoop\apps\ojdkbuild8-full\1.8.0.265-1.b01\_tmp\SourceDir\ojdkbuild\java-1.8.0-openjdk-1.8.0.265-1\missioncontrol\features\org.openjdk.jmc.feature.rcp.ja_7.1.1.202008301458\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.rcp.ja
=== Logging stopped: 9/2/2020  11:00:25 ===

**Comment by se35710** [comment]
See https://github.com/ScoopInstaller/Java/issues/191#issuecomment-687656385
