### ISSUE TITLE
ojdkbuild8-full@1.8.0.265-1.b01: decompress error

### ISSUE THREAD

**Issue by wangxianl** [ScoopInstaller/Java#193]
Failed to extract files from D:\ScoopApps\apps\ojdkbuild8-full\1.8.0.265-1.b01\java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi.
[msi.log](https://github.com/ScoopInstaller/Java/files/5165901/msi.log)

**Comment by se35710** [comment]
Please see https://github.com/ScoopInstaller/Java/issues/191#issuecomment-687656385
