### ISSUE TITLE
ojdkbuild8-full@1.8.0.265-1.b01: decompress error

### ISSUE THREAD

**Issue by leecloudvictor** [ScoopInstaller/Java#194]
=== Logging started: 2020/9/5  11:09:24 ===
Error 1304. Error writing to file: D:\dev\scoop\apps\ojdkbuild8-full\1.8.0.265-1.b01\_tmp\SourceDir\ojdkbuild\java-1.8.0-openjdk-1.8.0.265-1\missioncontrol\features\org.openjdk.jmc.feature.joverflow_1.0.1.202008301458\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.joverflow\pom.properties. Verify that you have access to that directory.
=== Logging stopped: 2020/9/5  11:09:26 ===

**Comment by se35710** [comment]
Please see https://github.com/ScoopInstaller/Java/issues/191#issuecomment-687656385
