### ISSUE TITLE
ojdkbuild8-full@1.8.0.265-1.b01: decompress error

### ISSUE THREAD

**Issue by songmy** [ScoopInstaller/Java#196]
=== Logging started: 2020/9/12  15:33:49 ===
Error 1320. The specified path is too long: F:\tools\scoop\base\apps\ojdkbuild8-full\1.8.0.265-1.b01\_tmp\SourceDir\ojdkbuild\java-1.8.0-openjdk-1.8.0.265-1\missioncontrol\features\org.openjdk.jmc.feature.rcp.ja_7.1.1.202008301458\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.rcp.ja
=== Logging stopped: 2020/9/12  15:33:50 ===

**Comment by qq523407234** [comment]
+1

**Comment by se35710** [comment]
Please run `scoop status` to check for potential problems and read the wiki at https://github.com/lukesampson/scoop/wiki/Java#ojdkbuild before submitting issues.
