### ISSUE TITLE
ojdkbuild8-full@1.8.0.265-1.b01: decompress error

### ISSUE THREAD

**Issue by yagodkin** [ScoopInstaller/Java#217]
=== Logging started: 11/3/2020  15:18:31 ===
Error 1320. The specified path is too long: C:\Users\yagodkin\scoop\apps\ojdkbuild8-full\1.8.0.265-1.b01\_tmp\SourceDir\ojdkbuild\java-1.8.0-openjdk-1.8.0.265-1\missioncontrol\features\org.openjdk.jmc.feature.rcp.ja_7.1.1.202008301458\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.rcp.ja
=== Logging stopped: 11/3/2020  15:18:34 ===

**Comment by se35710** [comment]
https://github.com/lukesampson/scoop/wiki/Java#ojdkbuild
