### ISSUE TITLE
ojdkbuild8-full@1.8.0.265-1.b01: decompress error

### ISSUE THREAD

**Issue by combucho** [ScoopInstaller/Java#222]
scoop install ojdkbuild8-full
Installing 'ojdkbuild8-full' (1.8.0.265-1.b01) [64bit]
Loading java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi from cache
Checking hash of java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi ... ok.
Extracting java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\Mi\scoop\apps\ojdkbuild8-full\1.8.0.265-1.b01\java-1.8.0-openjdk-1.8.0.265-1.b01.ojdkbuild.windows.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild8-full\1.8.0.265-1.b01\msi.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Java/issues/new?title=ojdkbuild8-full%401.8.0.265-1.b01%3a+decompress+error

---

cat scoop/apps/ojdkbuild8-full/1.8.0.265-1.b01/msi.log  
=== Logging started: 06.11.2020  21:18:24 ===
Error 1320. The specified path is too long: C:\Users\Mi\scoop\apps\ojdkbuild8-full\1.8.0.265-1.b01\_tmp\SourceDir\ojdkbuild\java-1.8.0-openjdk-1.8.0.265-1\missioncontrol\features\org.openjdk.jmc.feature.joverflow_1.0.1.202008301458\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.joverflow
=== Logging stopped: 06.11.2020  21:18:29 ===

**Comment by se35710** [comment]
https://github.com/lukesampson/scoop/wiki/Java#ojdkbuild
