### ISSUE TITLE
cannot use adoptopenjdk-lts-hotspot@11.0.9-11

### ISSUE THREAD

**Issue by kcris** [ScoopInstaller/Java#232]
I cannot use adoptopenjdk-lts-hotspot@11.0.9-11

```bash
scoop install adoptopenjdk-lts-hotspot@11.0.9-11
WARN  Given version (11.0.9-11) does not match manifest (11.0.9.1-1)
WARN  Attempting to generate manifest for 'adoptopenjdk-lts-hotspot' (11.0.9-11)
Autoupdating adoptopenjdk-lts-hotspot
Searching hash for OpenJDK$matchJdkU-jdk_x86-32_windows_hotspot_$matchMajor_$matchBuild.zip in https://github.com/$matchUrl/OpenJDK$matchJdkU-jdk_x86-32_windows_hotspot_$matchMajor_$matchBuild.zip.sha256.txt
Le serveur distant a retourné une erreur : (404) Introuvable.
URL https://github.com/$matchUrl/OpenJDK$matchJdkU-jdk_x86-32_windows_hotspot_$matchMajor_$matchBuild.zip.sha256.txt is not valid
Could not find hash in https://github.com/$matchUrl/OpenJDK$matchJdkU-jdk_x86-32_windows_hotspot_$matchMajor_$matchBuild.zip.sha256.txt
Downloading OpenJDK$matchJdkU-jdk_x86-32_windows_hotspot_$matchMajor_$matchBuild.zip to compute hashes!
Le serveur distant a retourné une erreur : (404) Introuvable.
URL https://github.com/$matchUrl/OpenJDK$matchJdkU-jdk_x86-32_windows_hotspot_$matchMajor_$matchBuild.zip is not valid
Could not find hash!
Could not install adoptopenjdk-lts-hotspot@11.0.9-11
```

Thank you

ps: unrelated question - why can I do `scoop search adoptopenjdk` and get some results *before* doing `scoop bucket add java`?
I was thinking that a package is only visible (in scoop search) if the bucket is added

**Comment by se35710** [comment]
Due to scoop autoupdate limitations, installing specific versions of AdoptOpenJDK does not work. You can via GitHub browse the history and download the manifest manually to install it with `scoop install .\adoptopenjdk-lts-hotspot.json`

The link for the manifest you were trying to install you can find here: https://github.com/ScoopInstaller/Java/raw/a8833fcc03c5dd5782ae30e14f1242932285794b/bucket/adoptopenjdk-lts-hotspot.json

**Comment by se35710** [comment]
Re you second question; scoop search goes through the buckets defined in [buckets.json](https://github.com/lukesampson/scoop/blob/master/buckets.json) + any additional buckets you have added if I remember correctly. For a definite answer, ask in [Discord](https://discord.gg/s9yRQHt) or [Gitter](https://gitter.im/lukesampson/scoop).
