### ISSUE TITLE
Include mvnd in the bucket

### ISSUE THREAD

**Issue by hemangajmera** [ScoopInstaller/Java#238]
Please add mvnd in the bucket. It makes maven runs much faster.

Here is the github link.
https://github.com/mvndaemon/mvnd

**Comment by se35710** [comment]
The [Main](https://github.com/ScoopInstaller/Main) or [Extras](https://github.com/lukesampson/scoop-extras) bucket would be better for this. This bucket is mostly for Java runtimes, utilities or closely related tools. Both [maven.json](https://github.com/ScoopInstaller/Main/blob/master/bucket/maven.json) and [gradle.json](https://github.com/ScoopInstaller/Main/blob/master/bucket/gradle.json) are in Main.
