### ISSUE TITLE
dragonwell8@8.5.5-275: hash check failed

### ISSUE THREAD

**Issue by tlj1339** [ScoopInstaller/Java#240]
Updating 'dragonwell8' (8.4.4-262 -> 8.5.5-275)
Downloading new version
Alibaba_Dragonwell_8.5.5-Experimental_Windows_x64.zip (99.1 MB) [==========================================================] 100%
Checking hash of Alibaba_Dragonwell_8.5.5-Experimental_Windows_x64.zip ... ERROR Hash check failed!
App:         java/dragonwell8
URL:         https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.5.5_jdk8u275-ga/Alibaba_Dragonwell_8.5.5-Experimental_Windows_x64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    25cc0788be4c9aa0e3e37ca0a9126afe9978690e339dcbb286433f7d211960e6
Actual:      1b7dfee90585c55cf1c6ce2f7229ad9da05e86c15d94aa687f2f789ad4364dad

**Comment by se35710** [comment]
Hash is taken from the release page of Dragonwell 8: https://github.com/alibaba/dragonwell8/releases/tag/dragonwell-8.5.5_jdk8u275-ga. I have the same actual checksum (1b7dfee90585c55cf1c6ce2f7229ad9da05e86c15d94aa687f2f789ad4364dad) when I download it here.

I submitted an issue so they can update the release: https://github.com/alibaba/dragonwell8/issues/156
