### ISSUE TITLE
ojdkbuild8-full@1.8.0.282-1.b08: decompress error

### ISSUE THREAD

**Issue by cyanthecomputerscientist** [ScoopInstaller/Java#247]
I've uninstalled and reinstalled multiple times and I get this strange error. 
![scoopJava](https://user-images.githubusercontent.com/66275150/106348396-0ac07900-6294-11eb-8836-e03f47e7c6bf.PNG)

**Comment by se35710** [comment]
Possibly a duplicate of #72

**Comment by cyanthecomputerscientist** [comment]
Thanks I appreciate it.
