### ISSUE TITLE
ojdkbuild8-full@1.8.0.282-1.b08: decompress error

### ISSUE THREAD

**Issue by Somiona** [ScoopInstaller/Java#248]
Installing 'ojdkbuild8-full' (1.8.0.282-1.b08) [64bit]
java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86_64.msi (208.9 MB) [==================================] 100%
Checking hash of java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86_64.msi ... ok.
Extracting java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86_64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\Somion\scoop\apps\ojdkbuild8-full\1.8.0.282-1.b08\java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild8-full\1.8.0.282-1.b08\msi.log

msi.log:

=== Logging started: 2021/2/11  14:47:32 ===
Error 1320. The specified path is too long: C:\Users\Somion\scoop\apps\ojdkbuild8-full\1.8.0.282-1.b08\_tmp\SourceDir\ojdkbuild\java-1.8.0-openjdk-1.8.0.282-1\missioncontrol\features\org.openjdk.jmc.feature.console_7.1.1.202101242338\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.console
=== Logging stopped: 2021/2/11  14:47:42 ===

**Comment by se35710** [comment]
See #72
