### ISSUE TITLE
zulu@16.30.15: hash check failed

### ISSUE THREAD

**Issue by cgassmann** [ScoopInstaller/Java#292]
Installing 'zulu' (16.30.15) [64bit]
zulu16.30.15-ca-jdk16.0.1-win_x64.zip (199.1 MB) [========================================================================] 100%
Checking hash of zulu16.30.15-ca-jdk16.0.1-win_x64.zip ... ERROR Hash check failed!
App:         java/zulu
URL:         https://cdn.azul.com/zulu/bin/zulu16.30.15-ca-jdk16.0.1-win_x64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    36a45d39b786af205b1150a03de4b8c9f3bcaa0feaac71f0b445353ada69f7d1
Actual:      42930e79a69736d2f2639f92cbb266c5c9b5f80f96a6f2f1422cd03e8e33b619

**Comment by se35710** [comment]
Fixed in https://github.com/ScoopInstaller/Java/commit/e3bc364415a0b49195ad5b871699fdf386374a56
