### ISSUE TITLE
ojdkbuild11-full@11.0.11.9-1: decompress error

### ISSUE THREAD

**Issue by mjdl** [ScoopInstaller/Java#293]
Installation failed with these console messages:

```
C:\Users\Mxxxxx>scoop install ojdkbuild11-full
Installing 'ojdkbuild11-full' (11.0.11.9-1) [64bit]
Loading java-11-openjdk-11.0.11.9-1.windows.ojdkbuild.x86_64.msi from cache
Checking hash of java-11-openjdk-11.0.11.9-1.windows.ojdkbuild.x86_64.msi ... ok.
Extracting java-11-openjdk-11.0.11.9-1.windows.ojdkbuild.x86_64.msi ... ERROR Exit code was 1603!
Failed to extract files from C:\Users\Mxxxxx\scoop\apps\ojdkbuild11-full\11.0.11.9-1\java-11-openjdk-11.0.11.9-1.windows.ojdkbuild.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild11-full\11.0.11.9-1\msi.log
```

Contents of msi.log:
```
=== Logging started: 2021-06-14  15:25:18 ===
Error 1320. The specified path is too long: C:\Users\Mxxxxx\scoop\apps\ojdkbuild11-full\11.0.11.9-1\_tmp\SourceDir\ojdkbuild\java-11-openjdk-11.0.11-1\missioncontrol\features\org.openjdk.jmc.feature.joverflow_1.0.1.202105012223\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.joverflow
=== Logging stopped: 2021-06-14  15:25:20 ===
```
Scoop is up to date on a Windows 10 Pro platform.

The [Windows "Long Paths"](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd) option has been enabled to allow a path length more than 260.  However, this requires the msi executable's manifest to include that option (see earlier link, I have no idea how to check this, and don't know much about Windows installers). So this might be an issue to settle with the builders of the ojdk msi installer in the ojdkbuild11-full package. (Maybe I can raise it with them with the little knowledge & information I have about the issue.)

Is the scoop package installation process designed to deal with potential paths >260 in length correctly, if the Windows user has enabled this option?

Meanwhile I've installed liberica11-full scoop package without issues.
Thanks for such a great program installation system!

**Comment by se35710** [comment]
See resolution in #72
