### ISSUE TITLE
zulu-jre@16.30.15: hash check failed

### ISSUE THREAD

**Issue by AntonOks** [ScoopInstaller/Java#294]
λ  scoop install zulu-jre
Installing 'zulu-jre' (16.30.15) [64bit]
zulu16.30.15-ca-jre16.0.1-win_x64.zip (43,7 MB) [=========================================================================================================================================================] 100%
Checking hash of zulu16.30.15-ca-jre16.0.1-win_x64.zip ... ERROR Hash check failed!
App:         java/zulu-jre
URL:         https://cdn.azul.com/zulu/bin/zulu16.30.15-ca-jre16.0.1-win_x64.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    5cd2fd12056579642b6a464dee343235a224c29976e7ff01a8d55ec6f288db84
Actual:      e259b19ebb215d326b160ce4372fc8ed245abd574ee81b1bc42719fedc0b2223

**Comment by se35710** [comment]
Fixed in https://github.com/ScoopInstaller/Java/commit/969a3a71bdbf6a84e401129ca02f8fbd1f993f27
