### ISSUE TITLE
ojdkbuild8-full@1.8.0.302-1.b08: decompress error

### ISSUE THREAD

**Issue by DylanWilson98** [ScoopInstaller/Java#301]
Failed to extract files from C:\Users\Dylan Wilson\scoop\apps\ojdkbuild8-full\1.8.0.302-1.b08\java-1.8.0-openjdk-1.8.0.302-1.b08.ojdkbuild.windows.x86_64.msi.
Log file:
  ~\scoop\apps\ojdkbuild8-full\1.8.0.302-1.b08\msi.log

**Comment by jtyus** [comment]
Did you figure out the problem? I'm having the same issue.

**Comment by DylanWilson98** [comment]
I ended up  not using scoop to download Java 8. I went directly through Oracle  to download it.
