### ISSUE TITLE
ojdkbuild8-full@1.8.0.302-1.b08: decompress error

### ISSUE THREAD

**Issue by SAngelle** [ScoopInstaller/Java#302]
I already had java installed however the app would not open so I decided to uninstall java completely and install java through scoop. I keep being told that I already installed java then I was told to uninstall java however it still giving me an Error 1603.

**Comment by se35710** [comment]
See https://github.com/ScoopInstaller/Java/issues/72#issuecomment-548238121 for a possible solution.

**Comment by snowman** [comment]
Thanks, @se35710 it works :tada:
