### ISSUE TITLE
Error on installing or updating microsoft-jdk

### ISSUE THREAD

**Issue by ricardobsp** [ScoopInstaller/Java#310]
I got an exception when I updated microsoft-jdk. Uninstalled and installed again and got the same exception:

Line |
 510 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'jdk-17.35.1+'! (error 16)

**Comment by PhyX-Meow** [comment]
same here

**Comment by cgassmann** [comment]
Proposed fix: https://github.com/ScoopInstaller/Java/pull/311

**Comment by se35710** [comment]
Fixed in #317
