### ISSUE TITLE
[question] other java development tools

### ISSUE THREAD

**Issue by phanirithvij2000** [ScoopInstaller/Java#339]
Do other java development tools belong in this bucket?

Like example https://github.com/pxb1988/dex2jar

**Comment by se35710** [comment]
Good question.

@ScoopInstaller/maintainers Should we move all Java-based software and tools to this repo?

**Comment by stevehipwell** [comment]
I think there is a clear distinction between the JDK/JRE, Java dev tools and software that depends on Java, but I don't think there is a reason to separate the latter two from other equivalent packages; taxonomy is almost as hard as naming and cache invalidation! For me this bucket is for the JDK/JRE packages, other packages for Java should live in the generic buckets such as main or extras.

**Comment by issaclin32** [comment]
I agree with @stevehipwell. Also, people have been used to searching for these tools in the *main* or *extras* bucket. Moving them into *Java* bucket can cause some trouble.

**Comment by phanirithvij2000** [comment]
Great, thanks for the clarification, hope this can be mentioned in the readme/wiki/or somewhere so that it is clear for new users.
