### ISSUE TITLE
What should I do after oraclejdk has been removed from java bucket?

### ISSUE THREAD

**Issue by Charlestar** [ScoopInstaller/Java#340]
Today when I try "scoop update *" and "scoop status", I get a message: 
```
These app manifests have been removed:
    oraclejdk
```
I find that "oraclejdk" is removed from the java bucket, I wonder whether this will cause some trouble to use java, and is there any solutions to solve this problem?

**Comment by pratikpc** [comment]
Transferred to Java as this seems like the correct place to discuss it

I agree with @PAStheLoD in this case.

We were facing issues and Oracle JDK was unmaintainable

https://github.com/ScoopInstaller/Java/issues/257#issuecomment-813879128
