### ISSUE TITLE
Suggestion: Add unique named shims

### ISSUE THREAD

**Issue by couleurm** [ScoopInstaller/Java#361]
Each of theses manifests overlap each other each time you install them, so one idea I had was to shim `java.exe` and `javaw.exe` but give their shim a different name, e.g for GraalVM JDK 17:

```json
    "bin": [
        [
      "bin\\javaw.exe",
      "graalvm-jdk17-javaw"
      ],
      [
        "bin\\java.exe",
        "graalvm-jdk17-java"
    ]
  ]
```

**Comment by tech189** [comment]
The wiki says that the recommended way is to have the overlap and then switch when you need to using `scoop reset x`. This is partly so that other programs can find `java`/`javaw`, I think. See: https://github.com/ScoopInstaller/Scoop/wiki/Java#switching-javas

**Comment by se35710** [comment]
Right now we only update `PATH` in the GraalVM manifests, which resets as explained in the [comment](https://github.com/ScoopInstaller/Java/issues/361#issuecomment-1009880327) above.

When I look at `PATH` on my own machine, the `shims` folder is right at the end of paths, so just providing a `graalvm-jdk17-javaw` shim would not help if there are multiple GraalVM manifests installed using the same shim name. `$version` expansion is not currently implemented to support `bin` arrays. One option would be to use the manifest name as prefix for the `java`/`javaw` binaries (`graalvm21-jdk17-javaw.exe`/`graalvm21-jdk17-java.exe`), however without a `scoop reset`, `JAVA_HOME` and `GRAALVM_HOME` will keep their value, and could potentially point to another GraalVM installation other than the version the shim executed points to.

**Comment by HUMORCE** [comment]
> scoop-shim: Add scoop shim to manipulate shims (https://github.com/ScoopInstaller/Scoop/issues/4727, https://github.com/ScoopInstaller/Scoop/issues/4736)
> 
> [v0.1.0 - 2022-03-01](https://github.com/ScoopInstaller/Scoop/blob/master/CHANGELOG.md#v010---2022-03-01)

Use `scoop shim` for this thing.
