### ISSUE TITLE
Liberica LTS manifests updated to new Java18 version but should remain on Java17

### ISSUE THREAD

**Issue by ShadowCreator250** [ScoopInstaller/Java#381]
The LTS versions should remain on the major version 17 of Java but the auto update updated the manifests to 18-37.

A quick search in the search directory shows that really nicely: https://scoopsearch.github.io/#/apps?q=liberica+lts

**Comment by se35710** [comment]
Upstream API issue: https://api.bell-sw.com/v1/liberica/releases?bundle-type=jdk&version-modifier=latest&release-type=lts&os=windows&arch=x86&installation-type=archive&package-type=zip&output=json&fields=version

**Comment by ShadowCreator250** [comment]
Thanks for checking that, I forgot.
The contact form on their website is not really fitting to report this. Idk how to report this in a proper way.
I just wrote a tweet to them, maybe it will help. lol

**Comment by ShadowCreator250** [comment]
They answered to my tweet & said they fixed it. I confirmed it with an API call & the scoop manifest is already on the correct version again.

I think we can close this issue.

**Comment by se35710** [comment]
Great! Thanks for helping out!
