### ISSUE TITLE
microsoft-lts-jdk@17.0.3: decompress error

### ISSUE THREAD

**Issue by vidarkongsli** [ScoopInstaller/Java#385]
**Troubleshooting before submitting**
- [x] Ran `scoop checkup` with no found problems?
- [x] Read the [wiki](https://github.com/lukesampson/scoop/wiki/Java) relevant for the manifest being installed?
- [x] Checked for [duplicate issues](https://github.com/ScoopInstaller/Java/issues?q=is%3Aissue), included closed ones?
- [x] Checked with [main scoop repo](https://github.com/lukesampson/scoop/issues) for related issues

**Describe the bug**
Does not install with error: 
```
Extracting microsoft-jdk-17.0.3-windows-x64.zip ... Exception: C:\Users\vkg\scoop\apps\scoop\current\lib\core.ps1:561
Line |
 561 |          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find 'jdk-17+0'! (error 16)
```

**To Reproduce**
1. Try to install

**Expected behavior**
1. Should install 
 
**Screenshots**

**Desktop (please complete the following information):**
 - Windows Version: Win 11 x64
 - Powershell Version: Core 7.2.2

**Additional context**

The problem is [here](https://github.com/ScoopInstaller/Java/blob/7105bb921c1384b276c1b39debe198c73d157d16/bucket/microsoft-lts-jdk.json#L12) where the value should be `jdk-17.0.3+7`.

**Comment by HUMORCE** [comment]
#384
