### ISSUE TITLE
[OUTDATED] OracleJre8- 8u321

### ISSUE THREAD

**Issue by Xelbayria** [ScoopInstaller/Java#388]
I've checked the website, the latest version is 8u333

the current version on the manifest is 8u321

It will need to be updated.

**Comment by se35710** [comment]
For some reason the 64-bit tar.gz download does not exist (https://javadl.oracle.com/webapps/download/AutoDL?BundleId=246475_2dee051a5d0647d5be72a7c0abff270e). As this is an error on Oracle's end, there is nothing we can do.
