### ISSUE TITLE
openjdk17@17.0.2-8: download via aria2 failed

### ISSUE THREAD

**Issue by omerakgoz34** [ScoopInstaller/Java#393]
ERROR Download failed! (Error 19) Name resolution failed
ERROR https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/openjdk-17.0.2_windows-x64_bin.zip
    referer=https://download.java.net/java/GA/jdk17.0.2/dfd4a8d0985749f896bed50d7138ee7f/8/GPL/
    dir=C:\Users\omerakgoz34\scoop\cache
    out=openjdk#17.0.2-8#https_download.java.net_java_GA_jdk17.0.2_dfd4a8d0985749f896bed50d7138ee7f_8_GPL_openjdk-17.0.2_windows-x64_bin.zip

ERROR & 'C:\Users\omerakgoz34\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\omerakgoz34\scoop\cache\openjdk.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/7.2 (Windows NT 10.0; Win64; x64; Core)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=8 --max-connection-per-server=8 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=3868 --continue --summary-interval=0 --auto-save-interval=1

**Comment by HUMORCE** [comment]
```
❯ scoop download openjdk17
INFO  Starting download for openjdk17...
openjdk-17.0.2_windows-x64_bin.zip (177.6 MB) [=======================================] 100%
Checking hash of openjdk-17.0.2_windows-x64_bin.zip ... ok.
'openjdk17' (17.0.2-8) was downloaded successfully!
```

may aria2 causing this problem, consider disabling it temporarily.

```
scoop config aria2-enabled False
scoop install openjdk17
scoop config aria2-enabled True
```
