### ISSUE TITLE
Unable to find manifest for "adoptopenjdk-hotspot"

### ISSUE THREAD

**Issue by LONEWALKER01** [ScoopInstaller/Java#410]
**Describe the bug**
Unable to find thee manifest for ```adoptopenjdk-hotspot``` and ```adoptopenjdk-hotspot-jre```

**To Reproduce**
scoop install adoptopenjdk-hotspot
and 
scoop install adoptopenjdk-hotspot-jre

**Expected behavior**
It should install

**Screenshots**
![image](https://user-images.githubusercontent.com/86109244/179369134-134f5a19-9516-409e-ae32-3af140e9e7d2.png)

**Desktop (please complete the following information):**
 - Windows Version: 10 LTSC
 - Powershell Version:5.1

**Comment by HUMORCE** [comment]
is `Java` bucket added?

```
scoop bucket list
```

**Comment by tech189** [comment]
Maybe the bucket is stuck in an out-of-date state - try removing it and adding it again with `scoop bucket rm java` and then `scoop bucket add java`

**Comment by d0gkiller87** [comment]
It's under the name of [Eclipse Temurin](https://en.wikipedia.org/wiki/Adoptium#History), corresponding to config files named with `temurinXXX.json` (e.g. [temurin-jdk.json](https://github.com/ScoopInstaller/Java/blob/master/bucket/temurin-jdk.json)) now
