### ISSUE TITLE
Java Temurin 17 not updated to the latest version in the bucket

### ISSUE THREAD

**Issue by mateusz-bajorek** [ScoopInstaller/Java#412]
**Troubleshooting before submitting**
- [x] Ran `scoop checkup` with no found problems?
- [x] Read the [wiki](https://github.com/lukesampson/scoop/wiki/Java) relevant for the manifest being installed?
- [x] Checked for [duplicate issues](https://github.com/ScoopInstaller/Java/issues?q=is%3Aissue), included closed ones?
- [x] Checked with [main scoop repo](https://github.com/lukesampson/scoop/issues) for related issues

**Describe the bug**
_this here is describing issue with Temurin 17, but it's possible it's related also to other Temurin versions_
In the repo/bucket, the current Temurin 17 JDK/JRE is 17.0.3 while the latest released version is 17.0.4
The updater script uses `https://api.adoptium.net/v3/assets/feature_releases/17/ga?jvm_impl=hotspot&heap_size=normal&os=windows&architecture=x64&image_type=jdk&project=jdk&vendor=eclipse&page_size=1&sort_order=DESC` to look for the release, and the site currently gives 17.0.4 version but the bucket isn't updated. Also, there is https://github.com/adoptium/temurin17-binaries/releases site that maybe could be used instead.

**Expected behavior**
Bucket is updated with the latest Temurin 17 version.

**Comment by nemuelle** [comment]
autoupdate broke with [this commit](https://github.com/ScoopInstaller/Scoop/commit/794f8a51aaaa3b0c6f868320ecaa9b4050e125cd)
replacing $page with (Get-Encoding($wc)).GetString($ev.SourceEventArgs.Result) is an ugly fix if you don't want to wait.

**Comment by niheaven** [comment]
The `checkver.script` is not well documented in wiki, and I forgot the case that one could use `checkver.url` w/ `checkver.script`. Will be fixed soon and documented in wiki.
