### ISSUE TITLE
`temurin-jdk` updates to Beta 19 releases instead of latest GA

### ISSUE THREAD

**Issue by magneticflux-** [ScoopInstaller/Java#419]
**Troubleshooting before submitting**
- [x] Ran `scoop checkup` with no found problems?
- [x] Read the [wiki](https://github.com/lukesampson/scoop/wiki/Java) relevant for the manifest being installed?
- [x] Checked for [duplicate issues](https://github.com/ScoopInstaller/Java/issues?q=is%3Aissue), included closed ones?
- [x] Checked with [main scoop repo](https://github.com/lukesampson/scoop/issues) for related issues

**Describe the bug**
The `temurin-jdk` app was updated past the current Temurin GA build (18) to a beta build (19).

**To Reproduce**
Update or install `temurin-jdk`.

**Expected behavior**
`temurin-jdk` should install the latest GA build.

**Screenshots**
```
temurin-jdk: 18.0.2-9 -> 19.0.0-beta-36.0.pre
Updating 'temurin-jdk' (18.0.2-9 -> 19.0.0-beta-36.0.pre)
...
Updating 2 outdated apps:
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: d93c22|OK  |    10MiB/s|C:/Users/Mitchell/scoop/cache/temurin-jdk#19.0.0-beta-36.0.pre#https_github.com_adoptium_temurin19-binaries_releases_download_jdk-19_36-RC1-beta_OpenJDK19U-jdk_x64_windows_hotspot_19_36-RC1.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of OpenJDK19U-jdk_x64_windows_hotspot_19_36-RC1.zip ... ok.
Uninstalling 'temurin-jdk' (18.0.2-9)
Installing 'temurin-jdk' (19.0.0-beta-36.0.pre) [64bit] from java bucket
Loading OpenJDK19U-jdk_x64_windows_hotspot_19_36-RC1.zip from cache.
Extracting OpenJDK19U-jdk_x64_windows_hotspot_19_36-RC1.zip ... Could not find 'jdk-19+36-RC1-beta'! (error 16)
At C:\Users\Mitchell\scoop\apps\scoop\current\lib\core.ps1:642 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...ta'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'jdk-19+36-RC1-beta'! (error 16)

Removing temurin-jdk: 19.0.0-beta-36.0.pre
```

**Desktop (please complete the following information):**
 - Windows Version: Windows 11 22H2 build 22622.575
 - Powershell Version: 7.2.6

**Additional context**
The `checkver` URL seems to return 1 entry; the nightly build of Java 19. This may be an upstream issue.

Relevant commits:
https://github.com/ScoopInstaller/Java/commit/16efaf87981d596ed77ac41f4a5f50d287ec4254
https://github.com/ScoopInstaller/Java/commit/f15df97711fff854e77cca8a8f62c39cfce9a053
https://github.com/ScoopInstaller/Java/commit/562a1db95db2bd84225b5927c482959960abf9c9
https://github.com/ScoopInstaller/Java/commit/fd9c340aa81ca81ba4f3897e973700ea6eedb527

**Comment by ParkerM** [comment]
I think this is fixed upstream now. https://api.adoptium.net/v3/assets/version/%5B8%2C%29?release_type=ga&jvm_impl=hotspot&heap_size=normal&os=windows&architecture=x64&image_type=jdk&project=jdk&vendor=eclipse&page_size=1&sort_order=DESC

**Comment by magneticflux-** [comment]
Fixed in:
https://github.com/ScoopInstaller/Java/commit/6aa3476b96fbd064ebeccebb4854d8293d50df41
https://github.com/ScoopInstaller/Java/commit/505186a3972c371607e66bd4145e325f303f5273
