### ISSUE TITLE
oraclejre8@8u351: decompress error

### ISSUE THREAD

**Issue by okibcn** [ScoopInstaller/Java#439]
#### Scoop Configuration

```json
{
  "aria2-warning-enabled": false,
  "last_update": "2022-10-18T16:11:58.3865411-07:00",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "scoop_branch": "master"
}
```

~\scoop\apps\oraclejre8\8u351\7zip.log
```log
7-Zip 22.01 (x64) : Copyright (c) 1999-2022 Igor Pavlov : 2022-07-15

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\Oki\scoop\apps\oraclejre8\8u351\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\Oki\scoop\apps\oraclejre8\8u351\dl.tar.gz
C:\Users\Oki\scoop\apps\oraclejre8\8u351\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive
```

**Comment by okibcn** [comment]
Please note that dl.tar.gz is a small 11 KB (11175 Byes) file, so it seems it is not downloading the right file, or the file is corrupted.

**Comment by BanHammerYKT** [comment]
> Please note that dl.tar.gz is a small 11 KB (11175 Byes) file, so it seems it is not downloading the right file, or the file is corrupted.

<details>
  <summary>the dl.tar.gz file is png</summary>
<img src="https://user-images.githubusercontent.com/5725779/196593929-9627e8ad-f986-45d2-bdef-f53d9d5380df.png">
</details>
