### ISSUE TITLE
can't open tlauncher with `oraclejre8` package

### ISSUE THREAD

**Issue by aicynide** [ScoopInstaller/Java#469]
## Bug Report

**Package Name:** [name of package which has bug(s)]

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by se35710** [comment]
Your software might require registry keys that are not updated when using Scoop.
