### ISSUE TITLE
[Windows] gu command is not available after installing graalvm

### ISSUE THREAD

**Issue by leviathan-n** [ScoopInstaller/Java#471]
## Bug Report
**Package Name:** [name of package which has bug(s)]
graalvm
### Current Behaviour
gu command is not available after installing graalvm, I can only reference it by the path name 

### Expected Behaviour
gu is available in shell

### Additional context/output
`..\graalvm\current\bin` is in the `$env:path` but 
`scoop which gu` output `'gu' not found / not a scoop shim.`

### System details

**Windows version:** [e.g. 7, 8, 10]

**OS architecture:** [e.g. 32bit, 64bit]

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
//# Your configuration here
```

**Comment by Small-Ku** [comment]
How about gu.cmd?

**Comment by leviathan-n** [comment]
That works!
Thanks a lot
