### ISSUE TITLE
[Request] Zulu21

### ISSUE THREAD

**Issue by Sacha00Z** [ScoopInstaller/Java#509]
## Package Request
Azul Zulu 21 (JDK/JRE) seems to be missing.
### Criteria

For a package to be acceptable in the Java bucket, it should be:

- [x] a runtime environment or software development kit for Java
- [x] a reasonably well-known and widely used developer tool (e.g. if it's a GitHub project, it should have at least 500 stars and 150 forks)
- [x] the latest stable version of the program
- [x] the full version i.e. not a trial version
- [x] a fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)
- [x] downloadable without having to sign in or use user-dependant cookies

### Information

**Name:** Azul Zulu: 21.32.17

**Description:** OpenJRE OpenJDK 21

**Homepage:** https://www.azul.com/

**Download link(s):** https://www.azul.com/downloads/?version=java-21-lts&os=windows&architecture=x86-64-bit&package=jdk#zulu 
https://www.azul.com/downloads/?version=java-21-lts&os=windows&architecture=x86-64-bit&package=jre#zulu

**Some indication of popularity/repute:** https://www.gartner.com/reviews/market/application-development-integration-and-management-others/vendor/azul-systems/product/zulu-enterprise

**License:** https://docs.azul.com/core/tpls/october-2023/zulu21_tpl.html

**Comment by eijckron** [comment]
Indeed odd that for zulu the dedicated versions stopped after zulu 17.
But especially for LTS version 21 it would be very nice if there is a dedicated installer.

**Comment by se35710** [comment]
Closed in PR #515
