### ISSUE TITLE
oraclejre8 8u431 fails to extract

### ISSUE THREAD

**Issue by denovodavid** [ScoopInstaller/Java#530]
## Bug Report

**Package Name:** oraclejre8

### Current Behaviour

Fails to extract archive.

### Expected Behaviour

Extracts archive.

### Additional context/output

The download link seems to be wrong, it doesn't download a valid archive. `8u421` works fine, but `8u431` is broken.
Here is log:
```

7-Zip 24.08 (x64) : Copyright (c) 1999-2024 Igor Pavlov : 2024-08-11

Scanning the drive for archives:
1 file, 11175 bytes (11 KiB)

Extracting archive: C:\Users\David\scoop\apps\oraclejre8\8u431\dl.tar.gz

Can't open as archive: 1
Files: 0
Size:       0
Compressed: 0
ERROR: C:\Users\David\scoop\apps\oraclejre8\8u431\dl.tar.gz
C:\Users\David\scoop\apps\oraclejre8\8u431\dl.tar.gz
Open ERROR: Cannot open the file as [gzip] archive


ERRORS:
Is not archive
```

### Possible Solution

...

### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:**
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  5007
```

**Additional software:** Windows Terminal

#### Scoop Configuration

```json
{
  "last_update": "2024-10-16T08:39:20.3039658+11:00",
  "aria2-warning-enabled": false,
  "scoop_branch": "master",
  "scoop_repo": "https://github.com/ScoopInstaller/Scoop",
  "aria2-enabled": false
}
```

**Comment by VivienDelmon** [comment]
The downloaded tarball seems very small

Directory: F:\scoop\apps\oraclejre8\8u431

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          16/10/2024    11:30           5304 7zip.log
-a---          16/10/2024    08:48          11175 dl.tar.gz

**Comment by se35710** [comment]
Downloading directly from the URL in the manifest seems to work, but it fails with Scoop. Need to investigate further.

**Comment by shoucandanghehe** [comment]
![image](https://github.com/user-attachments/assets/12bf622d-b2c2-43d6-b3fc-47922d7a27da)
Opening the url in the manifest in a browser will redirect to this image
This is the same one that scoop downloaded

**Comment by shoucandanghehe** [comment]
https://github.com/ScoopInstaller/Java/blob/b2b92e3a3d8aeae468c19e67c4cb05a52c23bcfa/bucket/oraclejre8.json#L8
It seems to be a BundleId error, should be `251408`

https://github.com/ScoopInstaller/Java/blob/b2b92e3a3d8aeae468c19e67c4cb05a52c23bcfa/bucket/oraclejre8.json#L12
32bit as well, should be `251407`

**Comment by se35710** [comment]
It seems the .tar.gz bundles are missing, 251408 and -7 are for .exe files, not for tar.gz.

**Comment by BinToss** [comment]
Parsing the EXEs for the installation files will be infeasible.

---

The EXE files' manifests contain the following:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="requireAdministrator" uiAccess="false" />
      </requestedPrivileges>
    </security>
  </trustInfo>
</assembly>
```

Searching the entire win x64 installer for the ASCII string `requireAdministrator` returns three results. Patching all of them to `asInvoker` (with padding so data isn't offset) "disables" the UAC prompt, but the executables will check for elevation and throw if their process isn't running with admin permissions. See jre-8u431-windows-x64.exe -> Binarycustomactions (type: DLL; Export: (7: IsUserAdmin))

Unpacking via 7-Zip will be impractical; most of the contents of Data1.cab are renamed and I'm unsure of where to look for the filenames (are they stored as hashes?).

If Oracle has intentionally ceased distribution of tarballs, we're SOL.

**Comment by BinToss** [comment]
https://helpx.adobe.com/coldfusion/kb/coldfusion-downloads.html#:~:text=JAVA%20SE%208U431%20RUNTIME%20ENVIRONMENT
Alternatively, Adobe redistributes JRE 8u431 in both EXE and ZIP forms without requiring sign-ins.
