### ISSUE TITLE
Cannot install Corretto and AdoptOpenJDK nightly with PowerShell Core

### ISSUE THREAD

**Issue by ttaomae** [ScoopInstaller/Java#57]
App manifests which use the script method of installation do not seem to work on PowerShell Core (6.1.3), but they seem to work fine on Windows PowerShell (5.1.17763.503). This includes Corretto and nightly AdoptOpenJDK distributions.

For example, here is the error I get on PowerShell Core when I run `scoop install java/coretto8`.
```
mv : Cannot find path 'C:\Users\<username>\scoop\apps\corretto8\8.212.04.2\tmp\C:\Users\<username>\scoop\apps\corretto8\8.212.04.2\tmp\jdk1.8.0_212' because it does not exist.
At line:1 char:27
+ gci -dir "$dir\tmp" | % { mv "$dir\tmp\$_\*" "$dir" }
+                           ~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:\Users\<username>\s...mp\jdk1.8.0_212:String) [Move-Item], ItemNotFoundException
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
```

I did a quick test and manually edited `~\scoop\buckets\java\bucket\corretto8.json`. I removed the `"extract_to"` and `"installer"` fields and added the field `"extract_dir": "jdk1.8.0_212"` and the installation seems to work.

**Comment by se35710** [comment]
Looks like `$_` expands to fullpath on PS Core.

For AdoptOpenJDK we have to use `Get-ChildItem`, the extract folder is very unpredictable.

**Comment by Ash258** [comment]
@se35710 Yes. On Core default toString for gci item is FullPath. Best practise:

```powershell
(gci -dir "$dir\tmp").FullName | % { Move-Item "$_\*" $dir }
```

This will make sure it is fullpath on pwsh and powershell

Sidenote: Not sure if it is fullname or fullpath
