### ISSUE TITLE
Why did you remove oraclejdk8 and oraclejdk8?

### ISSUE THREAD

**Issue by NoDocCat** [ScoopInstaller/Java#59]

**Comment by se35710** [comment]
If you can create a working manifest for oraclejdk8, please feel free to submit a pull request. Here is the download link: https://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

**Comment by se35710** [comment]
See https://github.com/ScoopInstaller/Java/issues/50
