### ISSUE TITLE
ojdkbuild12-full@12.0.1.12-1: decompress error

### ISSUE THREAD

**Issue by aierxing** [ScoopInstaller/Java#72]
=== Logging started: 2019-09-11  14:41:31 ===
Error 1304. Error writing to file: C:\Users\air\scoop\apps\ojdkbuild12-full\12.0.1.12-1\_tmp\SourceDir\ojdkbuild\java-12-openjdk-12.0.1-1\missioncontrol\features\org.openjdk.jmc.feature.rcp.zh_CN_7.0.0.v20190423-2115\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.rcp.zh_CN\pom.properties. Verify that you have access to that directory.
=== Logging stopped: 2019-09-11  14:41:35 ===

**Comment by se35710** [comment]
Run `scoop config MSIEXTRACT_USE_LESSMSI $true` and then uninstall, install.
