### ISSUE TITLE
ojdkbuild11-full@11.0.3.7-1: decompress error

### ISSUE THREAD

**Issue by leecloudvictor** [ScoopInstaller/Java#83]
=== Logging started: 2019/10/25  15:14:26 ===
Error 1320. The specified path is too long: D:\DEV\scoop\apps\ojdkbuild11-full\11.0.3.7-1\_tmp\SourceDir\ojdkbuild\java-11-openjdk-11.0.3-1\missioncontrol\features\org.openjdk.jmc.feature.flightrecorder_7.0.0.v20190423-2115\META-INF\maven\org.openjdk.jmc\org.openjdk.jmc.feature.flightrecorder
=== Logging stopped: 2019/10/25  15:14:28 ===

**Comment by se35710** [comment]
Run a `scoop checkup` to see if long path is enabled or not.
