### ISSUE TITLE
AdoptOpenJDK 13 stable

### ISSUE THREAD

**Issue by TyPh00nCdr** [ScoopInstaller/Java#84]
Can we get the latest stable versions of AdoptOpenJDK 13? Currently only the nightlies of Adopt13 are provided and [`adoptopenjdk-hotspot.json`](https://github.com/ScoopInstaller/Java/blob/master/bucket/adoptopenjdk-hotspot.json) & [`adoptopenjdk-openj9.json`](https://github.com/ScoopInstaller/Java/blob/master/bucket/adoptopenjdk-openj9.json) are still stuck at JDK 12.

- [Hotspot](https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/tag/jdk-13.0.1%2B9) (`v13.0.1+9`)
- [OpenJ9](https://github.com/AdoptOpenJDK/openjdk13-binaries/releases/tag/jdk-13.0.1%2B9_openj9-0.17.0) (`v13.0.1+9_openj9-0.17.0`)

**Comment by ParkerM** [comment]
I've also been waiting on this for a while, so I submitted #85 to add the `adopt13-*` releases.  
The PR doesn't include updates for `adoptopenjdk-hotspot` or `adoptopenjdk-openj9` yet, as there's a bit of a parity issue since 32-bit HotSpot builds are not yet available for `v13.0.1+9`.

**Comment by ParkerM** [comment]
Cool, I updated the HotSpot versions in the PR so they should all be at 13.0.1+9 now 👍.
